# # locators for mainpage
# site_header_main locators
MainLogo = "css:a.site-header__logo:nth-child(2) > img.lazyload"
BestSelleryLink = "css:header.site-header:nth-child(2) div.site-header__main:nth-child(4) div.wrapper.wrapper--row ul.main-menu:nth-child(3) li.main-menu__item:nth-child(1) > a.link.link--icon.link--icon-orange.link--blue.link--small"
NowosciLink = "css:header.site-header:nth-child(2) div.site-header__main:nth-child(4) div.wrapper.wrapper--row ul.main-menu:nth-child(3) li.main-menu__item:nth-child(2) > a.link.link--icon.link--icon-orange.link--blue.link--small"
WyspszedazLink = "//header/div[3]/div[1]/ul[1]/li[3]/a[1]"
KrotkieDatyLink = "//header/div[3]/div[1]/ul[1]/li[4]/a[1]"
SzukacLink = "//input[@id='autocompleteSearch']"
KoszykLink = "//header/div[3]/div[1]/ul[2]/li[2]/a[1]"
KontoLink = "//header/div[3]/div[1]/ul[2]/li[4]/a[1]"
MenuLink = "//header/div[3]/div[1]/ul[2]/li[5]/a[1]"

# slideshow_dot_wrapper locators
BlackWeekLink = "//li[contains(text(),'BLACK WEEK')]"
BlackWeekImg = "//body/main[@id='content']/div[@id='js-swiper-teaser']/ul[1]/li[2]/a[1]/img[1]"
BlackWeekLinkAfterClick = "//body/main[@id='content']/div[@id='js-swiper-teaser']/ul[1]/li[2]/a[1]"
ZimaZDozplLink = "//li[contains(text(),'ZIMA Z DOZ.PL')]"
ZimaZDozplImg = "//body/main[@id='content']/div[@id='js-swiper-teaser']/ul[1]/li[3]/a[1]/img[1]"
ZimaZDozplLinkAfterClick = "//body/main[@id='content']/div[@id='js-swiper-teaser']/ul[1]/li[3]/a[1]"
DlaMamyIDzieckaLink = "//li[contains(text(),'DLA MAMY I DZIECKA')]"
DlaMamyIDzieckaImg = "//body/main[@id='content']/div[@id='js-swiper-teaser']/ul[1]/li[4]/a[1]/img[1]"
DlaMamyIDzieckaLinkAfterClick = "//body/main[@id='content']/div[@id='js-swiper-teaser']/ul[1]/li[4]/a[1]"
UlgaDlaNogLink = "//li[contains(text(),'ULGA DLA NÓG')]"
UlgaDlaNogImg = "//body/main[@id='content']/div[@id='js-swiper-teaser']/ul[1]/li[4]/a[1]/img[1]"
UlgaDlaNogLinkAfterClick = "//body/main[@id='content']/div[@id='js-swiper-teaser']/ul[1]/li[5]/a[1]"
PielegnacjaLink = "//li[contains(text(),'PIELĘGNACJA')]"
PielegnacjaImg = "//body/main[@id='content']/div[@id='js-swiper-teaser']/ul[1]/li[4]/a[1]/img[1]"
PielegnacjaLinkAfterClick = "//body/main[@id='content']/div[@id='js-swiper-teaser']/ul[1]/li[6]/a[1]"
ZycieZCukrzycaLink = "//li[contains(text(),'ŻYCIE Z CUKRZYCĄ')]"
ZycieZCukrzycaImg = "//body/main[@id='content']/div[@id='js-swiper-teaser']/ul[1]/li[4]/a[1]/img[1]"
ZycieZCukrzycaLinkAfterClick = "//body/main[@id='content']/div[@id='js-swiper-teaser']/ul[1]/li[7]/a[1]"